// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu1HdqBXQjVOQJgyYqZWlw8WCDVwfcYFE',
    appId: '1:683165153860:web:6acfb581214bb2ace01a11',
    messagingSenderId: '683165153860',
    projectId: 'flutter-demo-42f1b',
    authDomain: 'flutter-demo-42f1b.firebaseapp.com',
    storageBucket: 'flutter-demo-42f1b.firebasestorage.app',
    measurementId: 'G-BCGM9PE2LD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg7nVQ5-8k57zhcMh-WFdKIaQNUXFo0p8',
    appId: '1:683165153860:android:e64e0a7a12caeda2e01a11',
    messagingSenderId: '683165153860',
    projectId: 'flutter-demo-42f1b',
    storageBucket: 'flutter-demo-42f1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPQPApnUxpxQ7MI4ro1yOJwxj9UvjZBKA',
    appId: '1:683165153860:ios:7373d775481b06dae01a11',
    messagingSenderId: '683165153860',
    projectId: 'flutter-demo-42f1b',
    storageBucket: 'flutter-demo-42f1b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseminer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPQPApnUxpxQ7MI4ro1yOJwxj9UvjZBKA',
    appId: '1:683165153860:ios:7373d775481b06dae01a11',
    messagingSenderId: '683165153860',
    projectId: 'flutter-demo-42f1b',
    storageBucket: 'flutter-demo-42f1b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseminer',
  );
}
